---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app excalidraw
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../shared/meta/components/gatus/external
    - ../../../../../shared/meta/components/volsync
  interval: 30m
  path: ./kubernetes/utility/apps/self-hosted/excalidraw/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: draw
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  timeout: 5m
  wait: false
