---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name jellystat-secret
spec:
  target:
    name: *name
    template:
      data:
        # App
        JWT_SECRET: "{{ .JWT_SECRET }}"
        # Maxmind
        JS_GEOLITE_ACCOUNT_ID: "{{ .MAXMIND_USER_ID }}"
        JS_GEOLITE_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
        # Database
        POSTGRES_IP: '{{ index . "pgbouncer-host" }}'
        POSTGRES_PORT: '{{ index . "pgbouncer-port" }}'
        POSTGRES_DB: '{{ .dbname }}'
        POSTGRES_USER: '{{ .user }}'
        POSTGRES_PASSWORD: '{{ .password }}'
  dataFrom:
  - extract:
      key: jellystat
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: bitwarden
  - extract:
      key: maxmind
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: bitwarden
  - extract:
      key: postgres-pguser-jellystat
    sourceRef:
      storeRef:
        name: crunchy-postgres
        kind: ClusterSecretStore
