---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app jellyfin
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../shared/meta/components/gatus/external
    - ../../../../../shared/meta/components/volsync
  interval: 30m
  path: ./kubernetes/main/apps/media/jellyfin/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: jf
      VOLSYNC_CAPACITY: 50Gi
      VOLSYNC_CACHE_CAPACITY: 25Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
